[build]
build-std = false                              # do not build the std library
zig = false                                    # do not use zig cc for the builds
default-target = "aarch64-unknown-linux-gnu"    # use this target if none is explicitly provided
pre-build = [                                  # additional commands to run prior to building the package
    "dpkg --add-architecture $CROSS_DEB_ARCH", 
    "apt-get update && apt-get --assume-yes install libssl-dev:$CROSS_DEB_ARCH libssl-dev libfontconfig1-dev libfontconfig1-dev:$CROSS_DEB_ARCH"
]     

[build.env]
passthrough = [
    "RUST_BACKTRACE",
    "RUST_LOG",
    "TRAVIS",
    "RUSTFLAGS",
    "PKG_CONFIG_SYSROOT_DIR"
]